# Generated by Django 3.0.6 on 2020-06-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bokdae_apt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_y', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=10)),
                ('dong', models.CharField(max_length=20)),
                ('bo_price', models.CharField(max_length=10)),
                ('mo_price', models.CharField(max_length=10)),
                ('apt_nm', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bokdae_office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_y', models.CharField(max_length=10)),
                ('offi_nm', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('dong', models.CharField(max_length=10)),
                ('bo_price', models.CharField(max_length=10)),
                ('mo_price', models.CharField(max_length=10)),
                ('floor', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bokdae_SH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_y', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=10)),
                ('dong', models.CharField(max_length=10)),
                ('bo_price', models.CharField(max_length=20)),
                ('mo_price', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('dataCreat', models.DateTimeField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
