# Generated by Django 3.0.6 on 2020-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigungu', models.CharField(max_length=200)),
                ('bunji', models.CharField(max_length=20)),
                ('doro', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=10)),
                ('jw', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=10)),
                ('deposit', models.CharField(max_length=20)),
                ('rent', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contents', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('dataCreat', models.DateTimeField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
